spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: false
      show-sql: flase
      properties:
        hibernate:
          format_sql: false